[2023-09-29T22:00:01.636+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_kalerkantho scheduled__2023-09-29T21:00:00+00:00 [queued]>
[2023-09-29T22:00:01.643+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_kalerkantho scheduled__2023-09-29T21:00:00+00:00 [queued]>
[2023-09-29T22:00:01.643+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-09-29T22:00:01.659+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_kalerkantho> on 2023-09-29 21:00:00+00:00
[2023-09-29T22:00:01.665+0000] {standard_task_runner.py:57} INFO - Started process 977 to run task
[2023-09-29T22:00:01.670+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_Pipeline', 'extract_kalerkantho', 'scheduled__2023-09-29T21:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/news_aggregator_dag.py', '--cfg-path', '/tmp/tmp947v51yr']
[2023-09-29T22:00:01.672+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask extract_kalerkantho
[2023-09-29T22:00:01.730+0000] {task_command.py:415} INFO - Running <TaskInstance: ETL_Pipeline.extract_kalerkantho scheduled__2023-09-29T21:00:00+00:00 [running]> on host 8b9d74f8b315
[2023-09-29T22:00:01.858+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_Pipeline' AIRFLOW_CTX_TASK_ID='extract_kalerkantho' AIRFLOW_CTX_EXECUTION_DATE='2023-09-29T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-29T21:00:00+00:00'
[2023-09-29T22:00:01.868+0000] {extract.py:22} ERROR - Could not fetch content due to error: HTTPSConnectionPool(host='www.kalerkantho.com', port=443): Max retries exceeded with url: /sitemap.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9112b32190>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2023-09-29T22:00:01.875+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/extract.py", line 52, in parse_from_kalerkantho
    latest_news_sitemap = sitemap_soup.find_all("loc")[1].text
AttributeError: 'NoneType' object has no attribute 'find_all'
[2023-09-29T22:00:01.887+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_Pipeline, task_id=extract_kalerkantho, execution_date=20230929T210000, start_date=20230929T220001, end_date=20230929T220001
[2023-09-29T22:00:01.911+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 26 for task extract_kalerkantho ('NoneType' object has no attribute 'find_all'; 977)
[2023-09-29T22:00:01.931+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-29T22:00:01.960+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-29T22:02:44.961+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_kalerkantho scheduled__2023-09-29T21:00:00+00:00 [queued]>
[2023-09-29T22:02:44.977+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_kalerkantho scheduled__2023-09-29T21:00:00+00:00 [queued]>
[2023-09-29T22:02:44.977+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-09-29T22:02:45.026+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_kalerkantho> on 2023-09-29 21:00:00+00:00
[2023-09-29T22:02:45.046+0000] {standard_task_runner.py:57} INFO - Started process 1036 to run task
[2023-09-29T22:02:45.058+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_Pipeline', 'extract_kalerkantho', 'scheduled__2023-09-29T21:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/news_aggregator_dag.py', '--cfg-path', '/tmp/tmp7cl3jtov']
[2023-09-29T22:02:45.063+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask extract_kalerkantho
[2023-09-29T22:02:45.160+0000] {task_command.py:415} INFO - Running <TaskInstance: ETL_Pipeline.extract_kalerkantho scheduled__2023-09-29T21:00:00+00:00 [running]> on host 8b9d74f8b315
[2023-09-29T22:02:45.339+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_Pipeline' AIRFLOW_CTX_TASK_ID='extract_kalerkantho' AIRFLOW_CTX_EXECUTION_DATE='2023-09-29T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-29T21:00:00+00:00'
[2023-09-29T22:02:45.352+0000] {extract.py:22} ERROR - Could not fetch content due to error: HTTPSConnectionPool(host='www.kalerkantho.com', port=443): Max retries exceeded with url: /sitemap.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9112b1b850>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2023-09-29T22:02:45.353+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/extract.py", line 52, in parse_from_kalerkantho
    latest_news_sitemap = sitemap_soup.find_all("loc")[1].text
AttributeError: 'NoneType' object has no attribute 'find_all'
[2023-09-29T22:02:45.375+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_Pipeline, task_id=extract_kalerkantho, execution_date=20230929T210000, start_date=20230929T220244, end_date=20230929T220245
[2023-09-29T22:02:45.399+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 32 for task extract_kalerkantho ('NoneType' object has no attribute 'find_all'; 1036)
[2023-09-29T22:02:45.445+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-29T22:02:45.469+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-29T22:04:05.189+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_kalerkantho scheduled__2023-09-29T21:00:00+00:00 [queued]>
[2023-09-29T22:04:05.203+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_kalerkantho scheduled__2023-09-29T21:00:00+00:00 [queued]>
[2023-09-29T22:04:05.203+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-09-29T22:04:05.228+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_kalerkantho> on 2023-09-29 21:00:00+00:00
[2023-09-29T22:04:05.241+0000] {standard_task_runner.py:57} INFO - Started process 1069 to run task
[2023-09-29T22:04:05.247+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_Pipeline', 'extract_kalerkantho', 'scheduled__2023-09-29T21:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/news_aggregator_dag.py', '--cfg-path', '/tmp/tmpwbxxbmio']
[2023-09-29T22:04:05.249+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask extract_kalerkantho
[2023-09-29T22:04:05.402+0000] {task_command.py:415} INFO - Running <TaskInstance: ETL_Pipeline.extract_kalerkantho scheduled__2023-09-29T21:00:00+00:00 [running]> on host 8b9d74f8b315
[2023-09-29T22:04:05.575+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_Pipeline' AIRFLOW_CTX_TASK_ID='extract_kalerkantho' AIRFLOW_CTX_EXECUTION_DATE='2023-09-29T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-29T21:00:00+00:00'
[2023-09-29T22:04:06.731+0000] {extract.py:55} INFO - Extracted URLs from Kaler Kantho. Total URLs: 130
[2023-09-29T22:04:06.731+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-09-29T22:04:06.746+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=ETL_Pipeline, task_id=extract_kalerkantho, execution_date=20230929T210000, start_date=20230929T220405, end_date=20230929T220406
[2023-09-29T22:04:06.819+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-29T22:04:06.849+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-29T22:12:36.569+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_kalerkantho scheduled__2023-09-29T21:00:00+00:00 [queued]>
[2023-09-29T22:12:36.583+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_kalerkantho scheduled__2023-09-29T21:00:00+00:00 [queued]>
[2023-09-29T22:12:36.584+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-09-29T22:12:36.605+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_kalerkantho> on 2023-09-29 21:00:00+00:00
[2023-09-29T22:12:36.615+0000] {standard_task_runner.py:57} INFO - Started process 1212 to run task
[2023-09-29T22:12:36.618+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_Pipeline', 'extract_kalerkantho', 'scheduled__2023-09-29T21:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/news_aggregator_dag.py', '--cfg-path', '/tmp/tmpyzbsb_ja']
[2023-09-29T22:12:36.620+0000] {standard_task_runner.py:85} INFO - Job 41: Subtask extract_kalerkantho
[2023-09-29T22:12:36.681+0000] {task_command.py:415} INFO - Running <TaskInstance: ETL_Pipeline.extract_kalerkantho scheduled__2023-09-29T21:00:00+00:00 [running]> on host 8b9d74f8b315
[2023-09-29T22:12:36.783+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_Pipeline' AIRFLOW_CTX_TASK_ID='extract_kalerkantho' AIRFLOW_CTX_EXECUTION_DATE='2023-09-29T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-29T21:00:00+00:00'
[2023-09-29T22:12:38.084+0000] {extract.py:55} INFO - Extracted URLs from Kaler Kantho. Total URLs: 130
[2023-09-29T22:12:38.084+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-09-29T22:12:38.094+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=ETL_Pipeline, task_id=extract_kalerkantho, execution_date=20230929T210000, start_date=20230929T221236, end_date=20230929T221238
[2023-09-29T22:12:38.121+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-29T22:12:38.149+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-09-29T22:54:43.085+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_kalerkantho scheduled__2023-09-29T21:00:00+00:00 [queued]>
[2023-09-29T22:54:43.094+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_kalerkantho scheduled__2023-09-29T21:00:00+00:00 [queued]>
[2023-09-29T22:54:43.094+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-09-29T22:54:43.114+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_kalerkantho> on 2023-09-29 21:00:00+00:00
[2023-09-29T22:54:43.122+0000] {standard_task_runner.py:57} INFO - Started process 143 to run task
[2023-09-29T22:54:43.125+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_Pipeline', 'extract_kalerkantho', 'scheduled__2023-09-29T21:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/news_aggregator_dag.py', '--cfg-path', '/tmp/tmp08hvc65c']
[2023-09-29T22:54:43.130+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask extract_kalerkantho
[2023-09-29T22:54:43.191+0000] {task_command.py:415} INFO - Running <TaskInstance: ETL_Pipeline.extract_kalerkantho scheduled__2023-09-29T21:00:00+00:00 [running]> on host 4e50881e96f5
[2023-09-29T22:54:43.306+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_Pipeline' AIRFLOW_CTX_TASK_ID='extract_kalerkantho' AIRFLOW_CTX_EXECUTION_DATE='2023-09-29T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-29T21:00:00+00:00'
[2023-09-29T22:54:44.227+0000] {extract.py:55} INFO - Extracted URLs from Kaler Kantho. Total URLs: 130
[2023-09-29T22:54:44.227+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-09-29T22:54:44.236+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=ETL_Pipeline, task_id=extract_kalerkantho, execution_date=20230929T210000, start_date=20230929T225443, end_date=20230929T225444
[2023-09-29T22:54:44.261+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-29T22:54:44.282+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
